mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('nutrition.urls'), name='home'),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('registration.urls'), name='registration'),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'  # namespacing for organization
# path uses url name, view function that returns an HTTP response, kwargs, and a global name for your url
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create', views.QuestionCreate.as_view(), name='create-polls'),
    path('create2', views.ChoiceCreate.as_view(), name='create-choice'),
    path('updateQ/<int:pk>', views.QuestionUpdate.as_view(), name='update-question'),
    path('updateC', views.ChoiceUpdate.as_view(), name='update-choice')
]

mysite/registration/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "register"

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('logout', views.logout_view, name='logout'),
    path('login', views.MyLoginView.as_view(), name='login'),
]

mysite/polls/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=timezone.now)

    def was_published_recently(self):
        return self.pub_date >= timezone.now()

    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return reverse('polls:index')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    def get_absolute_url(self):
        return reverse('polls:detail', args=str(self.question.pk))

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Question, Choice

# Create your views here.
from django.http import HttpResponse, Http404, HttpResponseRedirect


# generic ListView requires the list and template_name as well as the function for making the list
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    '''
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    # shortcut for above is get_object_or_404(model_name, attribute for get function)
    return render(request, 'polls/detail.html', {'question': question})
    '''
    model = Question
    template_name = 'polls/detail.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except KeyError:
        return render(request, 'polls/detail.html', {'question': question,
                                                     'error_message': "You didn't select a choice."})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


class QuestionCreate(LoginRequiredMixin, generic.CreateView):
    model = Question
    fields = ['question_text']


class ChoiceCreate(LoginRequiredMixin, generic.CreateView):
    model = Choice
    fields = ['question', 'choice_text']


class QuestionUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Question
    fields = ['question_text']


class ChoiceUpdate(LoginRequiredMixin, generic.CreateView):
    model = Choice
    fields = ['question', 'choice_text']

mysite/polls/templates/polls/choice_form.html
{% extends 'polls/index.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

{% block polls %}{% endblock %}

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
        <div>
            <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'polls:update-question' question.id %}" role="button">Update Question</a>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'polls:update-choice' %}">Add Choices</a>
        </div>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>
  <body>
    <header>
        {% if user.is_authenticated %}
            <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
                <a class="navbar-brand" href="{% url 'polls:index' %}">Polls</a>
                {% block middle %}
                    <div class="topnav-centered">Home</div>
                {% endblock %}
                <ul class="navbar-nav mr-only">
                    <li class="nav-item"><a class="nav-link" href="{% url 'register:logout' %}">Logout</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Profile - {{ user.username }}</a></li>
                </ul>
            </nav>
        {% else %}
        {% block navbar %}
            <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
                <a class="navbar-brand" href="{% url 'polls:index' %}">Polls</a>
                {% block middle2 %}
                    <div class="topnav-centered">Home</div>
                {% endblock %}
                <ul class="navbar-nav mr-only">
                    <li class="nav-item"><a class="nav-link" href="{% url 'register:login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'register:signup' %}">Sign Up</a></li>
                </ul>
            </nav>
        {% endblock %}
        {% endif %}
    </header>

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <div class="alert alert-success" roles="alert">{{ message }}</div>
            {% endif %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" roles="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}

    {% block content %} {% endblock %}

    {% block polls %}
        {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

mysite/polls/templates/polls/question_form.html
{% extends 'polls/index.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

{% block polls %}{% endblock %}

mysite/polls/templates/polls/results.html
{% extends "polls/index.html" %}
{% block middle %}
    <div class="topnav-centered">Results</div>
{% endblock %}

{% block content %}
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
{% endblock %}
{% block polls %}{% endblock %}

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/polls/templates/polls/vote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote Again?</a>
</body>
</html>