mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('nutrition.urls'), name='home'),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('registration.urls'), name='registration'),
]

mysite/nutrition/urls.py
from django.urls import path
from . import views

app_name = "nutrition"

urlpatterns = [
    path('food-list/<str:date_w>', views.FoodListView, name='food-list'),
    path('food-detail/<slug:slug>', views.detail, name='food-detail'),
    path('food-create', views.CreateFoodView.as_view(), name='food-create'),
    path('food-update/<slug:slug>', views.UpdateFoodView.as_view(), name='food-update'),
    path('food-delete/<slug:slug>', views.DeleteFoodView.as_view(), name='food-delete'),
    path('date-change', views.ChangeDateView, name="change-date")
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'  # namespacing for organization
# path uses url name, view function that returns an HTTP response, kwargs, and a global name for your url
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create', views.QuestionCreate.as_view(), name='create-polls'),
    path('create2', views.ChoiceCreate.as_view(), name='create-choice'),
    path('updateQ/<int:pk>', views.QuestionUpdate.as_view(), name='update-question'),
    path('updateC', views.ChoiceUpdate.as_view(), name='update-choice')
]

mysite/registration/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "register"

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('logout', views.logout_view, name='logout'),
    path('login', views.MyLoginView.as_view(), name='login'),
]

mysite/nutrition/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils.text import slugify
import re, requests
from django.http import HttpResponseRedirect


class Food(models.Model):
    name = models.CharField(max_length=200)
    date = models.DateField(default=datetime.date.today)
    meal = models.CharField(max_length=2,
                            choices=[('BR', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner'), ('SN', 'Snacks')],
                            default='BR')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    slug = models.SlugField(null=True)

    def __str__(self):
        return self.name

    # for CreateView to create a url path to newly created Food objects
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("nutrition:food-detail", kwargs={"slug": self.slug})

    # saving Food objects to database
    def save(self, *args, **kwargs):
        self.name = self.name.lower()  # makes all food names lowercase for consistency
        self.slug = slugify(self.name)
        # FIXME - self.slug should be like below
        # self.slug = str(self.meal) + "-" + slugify(self.name) + "-" + str(self.date)
        super(Food, self).save(*args, **kwargs)

    # gets nutrition data about food from API
    def getData(self, name):
        id = 'e302d382'
        key = '1de405bcf0d2f70a5ca5b0a4724261ae'
        code = re.sub(r'\s+', '%20', self.name)
        response = requests.get(
            "https://api.edamam.com/api/nutrition-data?app_id={0}&app_key={1}&ingr=%20{2}".format(id, key, code))
        json_data = response.json()


# Model for changing date of food object you want to see
class Date(models.Model):
    date = models.DateField(default=datetime.date.today)

mysite/nutrition/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils.text import slugify
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .models import Food
import requests, re
from datetime import datetime

# API ID and Key
id = '61654da9'
key = '2bc123f14ee26003008a336ca46f5d5b'
# default date used for many pages
date = str(datetime.today().date())


# function for retrieving nutritional info for detail view
def Summary(food_list):
    calories = str(sum([food['calories'] for food in food_list])) + " calories"
    fat = str(round(sum([food['totalNutrients']['FAT']['quantity'] for food in food_list]), 3)) + " g"
    carbs = str(round(sum([food['totalNutrients']['CHOCDF']['quantity'] for food in food_list]), 3)) + " g"
    protein = str(round(sum([food['totalNutrients']['PROCNT']['quantity'] for food in food_list]), 3)) + " g"
    return {'calories': calories, 'fat': fat, 'carbs': carbs, 'protein': protein}


# list of foods eaten on a day on homepage
@login_required
def FoodListView(request, date_w):
    # if user wants to change the date they're viewing, this will handle it
    if request.method == 'POST':
        date_w = request.POST['date']

    # getting foods by meal from local database
    date_conv = datetime.strptime(str(date_w), '%Y-%m-%d').date()
    breakfast = Food.objects.filter(user=request.user, meal='BR', date=date_conv)
    lunch = Food.objects.filter(user=request.user, meal='LU', date=date_conv)
    dinner = Food.objects.filter(user=request.user, meal='DI', date=date_conv)
    snacks = Food.objects.filter(user=request.user, meal='SN', date=date_conv)

    # List of food's json objects from particular meal. JSON was pulled from Edamam API that gives nutritonal info.
    breakfast_data = [requests.get(
        "https://api.edamam.com/api/nutrition-data?app_id={0}&app_key={1}&ingr=%20{2}".format(id, key, code)).json()
                      for code in [re.sub(r'\s+', '%20', food.name) for food in breakfast]]
    lunch_data = [requests.get(
        "https://api.edamam.com/api/nutrition-data?app_id={0}&app_key={1}&ingr=%20{2}".format(id, key, code)).json()
                      for code in [re.sub(r'\s+', '%20', food.name) for food in lunch]]
    dinner_data = [requests.get(
        "https://api.edamam.com/api/nutrition-data?app_id={0}&app_key={1}&ingr=%20{2}".format(id, key, code)).json()
                      for code in [re.sub(r'\s+', '%20', food.name) for food in dinner]]
    snacks_data = [requests.get(
        "https://api.edamam.com/api/nutrition-data?app_id={0}&app_key={1}&ingr=%20{2}".format(id, key, code)).json()
                      for code in [re.sub(r'\s+', '%20', food.name) for food in snacks]]

    # food data for all foods
    food_data = [requests.get(
        "https://api.edamam.com/api/nutrition-data?app_id={0}&app_key={1}&ingr=%20{2}".format(id, key, code)).json()
                      for code in
                      [re.sub(r'\s+', '%20', food.name) for food in Food.objects.filter(user=request.user,
                                                                                        date=date_conv)]]

    # food data totals
    total_data = Summary(food_data)

    return render(request, 'nutrition/Food_list.html', {'breakfast': breakfast, "lunch": lunch, "dinner": dinner,
                                                        "snacks": snacks, 'breakfast_data': breakfast_data,
                                                        'lunch_data': lunch_data, 'dinner_data': dinner_data,
                                                        'snacks_data': snacks_data, "total_data": total_data,
                                                        "date": date_w})


# gives detailed nutrition info about singular Food
def detail(request, slug):
    food = get_object_or_404(Food, slug=slug)
    code = re.sub(r'\s+', '%20', food.name)
    response = requests.get(
        "https://api.edamam.com/api/nutrition-data?app_id={0}&app_key={1}&ingr=%20{2}".format(id, key, code))
    json_data = response.json()
    return render(request, 'nutrition/Food_detail.html', {'object': food, 'data': json_data, 'date': date})


# Form for adding new foods to food list
class CreateFoodView(CreateView):
    template_name = "nutrition/Food_form.html"
    model = Food
    fields = ['name', 'date', 'meal']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "date": date
        })
        return context

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return HttpResponseRedirect(obj.get_absolute_url())


# Updates already created Food
class UpdateFoodView(UpdateView):
    model = Food
    context_object_name = 'food'
    fields = ['name', 'date', 'meal']
    template_name = "nutrition/Food_update.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "date": str(date)
        })
        return context


# Takes slug from delete url and identifies which Food to delete using given template
class DeleteFoodView(DeleteView):
    model = Food
    context_object_name = 'food'
    template_name = "nutrition/Food_delete.html"
    success_url = "/food-list/{}".format(date)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "date": str(date)
        })
        return context


def ChangeDateView(request):
    return render(request, "nutrition/ChangeDate.html", {"date": date})

mysite/nutrition/templates/nutrition/ChangeDate.html
{% extends "nutrition/base.html" %}
{% block content %}
    <form action="{% url 'nutrition:food-list' date %}" method="post">
        {% csrf_token %}
        <h1>Enter a Date:</h1>
        <input type="date" name="date" id="date" value="{{ date }}">
        <input type="submit" value="Submit">
    </form>
{% endblock %}

mysite/nutrition/templates/nutrition/Food_delete.html
{% extends 'nutrition/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p><big><b>Are you sure you want to delete "{{ food.name }}"?</b></big></p>
        <input class="btn btn-danger btn-sm mt-1 mb-1" type="submit" value="Confirm">
    </form>
{% endblock %}

mysite/nutrition/templates/nutrition/Food_detail.html
{% extends "nutrition/base.html" %}
{% block content %}
<h2><u>{{ object.name }}</u></h2>
    <ul>
        <li><b>Calories:</b> {{ data.calories }}</li>
        <li><b>Total Fat:</b> {{ data.totalNutrients.FAT.quantity|floatformat:3 }} {{ data.totalNutrients.FAT.unit }} </li>
        <ul>
            <li><b>Monounsaturated Fat:</b> {{ data.totalNutrients.FASAT.quantity|floatformat:3 }} {{ data.totalNutrients.FASAT.unit }} </li>
            <li><b>Polyunsaturated Fat:</b> {{ data.totalNutrients.FAMS.quantity|floatformat:3 }} {{ data.totalNutrients.FAMS.unit }} </li>
        </ul>
        <li><b>Total Carbohydrates:</b> {{ data.totalNutrients.CHOCDF.quantity|floatformat:3 }} {{ data.totalNutrients.CHOCDF.unit }} </li>
        <ul>
            <li><b>Fiber:</b> {{ data.totalNutrients.FIBTG.quantity|floatformat:3 }} {{ data.totalNutrients.FIBTG.unit }} </li>
            <li><b>Sugar:</b> {{ data.totalNutrients.SUGAR.quantity|floatformat:3 }} {{ data.totalNutrients.SUGAR.unit }} </li>
        </ul>
        <li><b>Protein:</b> {{ data.totalNutrients.PROCNT.quantity|floatformat:3 }} {{ data.totalNutrients.PROCNT.unit }} </li>
    </ul>
{% endblock %}

mysite/nutrition/templates/nutrition/Food_form.html
{% extends 'nutrition/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

mysite/nutrition/templates/nutrition/Food_list.html
{% extends "nutrition/base.html" %}
{% block date %} <h1>{{ date }}</h1>{% endblock %}
{% block content %}
    <div id="wrapper">
        <div id="first">
            <h2>Breakast</h2>
            {% for food in breakfast_data %}
                <ul class="list-group">
                    <li class="list-group-item-action">
                        <a href="{% url 'nutrition:food-detail' food.ingredients.0.text|slugify %}">{{ food.ingredients.0.text }} - Calories: {{ food.calories }} </a>
                        <a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'nutrition:food-update' food.ingredients.0.text|slugify %}"
                           role="button"> Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'nutrition:food-delete' food.ingredients.0.text|slugify %}"
                           role="button"> Delete</a>
                    </li>
                </ul>
            {% empty %}
                <p>No breakfast items added.</p>
            {% endfor %}

            <h2>Lunch</h2>
            {% for food in lunch_data %}
                <ul class="list-group">
                    <li class="list-group-item-action">
                        <a href="{% url 'nutrition:food-detail' food.ingredients.0.text|slugify %}">{{ food.ingredients.0.text }} - Calories: {{ food.calories }} </a>
                        <a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'nutrition:food-update' food.ingredients.0.text|slugify %}"
                           role="button"> Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'nutrition:food-delete' food.ingredients.0.text|slugify %}"
                           role="button"> Delete</a>
                    </li>
                </ul>
            {% empty %}
                <p>No lunch items added.</p>
            {% endfor %}

            <h2>Dinner</h2>
            {% for food in dinner_data %}
                <ul class="list-group">
                    <li class="list-group-item-action">
                        <a href="{% url 'nutrition:food-detail' food.ingredients.0.text|slugify %}">{{ food.ingredients.0.text }} - Calories: {{ food.calories }} </a>
                        <a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'nutrition:food-update' food.ingredients.0.text|slugify %}"
                           role="button"> Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'nutrition:food-delete' food.ingredients.0.text|slugify %}"
                           role="button"> Delete</a>
                    </li>
                </ul>
            {% empty %}
                <p>No dinner items added.</p>
            {% endfor %}

            <h2>Snacks</h2>
            {% for food in snacks_data %}
                <ul class="list-group">
                    <li class="list-group-item-action">
                        <a href="{% url 'nutrition:food-detail' food.ingredients.0.text|slugify %}">{{ food.ingredients.0.text }} - Calories: {{ food.calories }} </a>
                        <a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'nutrition:food-update' food.ingredients.0.text|slugify %}"
                           role="button"> Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'nutrition:food-delete' food.ingredients.0.text|slugify %}"
                           role="button"> Delete</a>
                    </li>
                </ul>
            {% empty %}
                <p>No snack items added.</p>
            {% endfor %}
            <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'nutrition:food-create' %}" role="button">Add Food</a>
        </div>

        <div class="card" style="width: 18rem;" id="second">
          <div class="card-body">
            <h2 class="card-title">Basic Summary</h2>
            <p>Total Calories: {{ total_data.calories }}</p>
            <p>Total Fat: {{ total_data.fat }}</p>
            <p>Total Carbohydrates: {{ total_data.carbs }}</p>
            <p>Total Protein: {{ total_data.protein }}</p>
            <a href="{% url 'nutrition:change-date'%}" class="btn btn-primary">Change Date</a>
          </div>
        </div>
    </div>
{% endblock %}

mysite/nutrition/templates/nutrition/Food_update.html
{% extends 'nutrition/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

mysite/nutrition/templates/nutrition/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <link rel="stylesheet" type="text/css" href = "{% static 'nutrition/style.css' %}">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>
  <body>
    <header>
        {% if user.is_authenticated %}
            <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
                <a class="navbar-brand" href="{% url 'nutrition:food-list' date %}">Nutrition Tracker</a>
                {% block middle %}
                    <div class="topnav-centered"></div>
                {% endblock %}
                <ul class="navbar-nav mr-only">
                    <li class="nav-item"><a class="nav-link" href="{% url 'register:logout' %}">Logout</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Profile - {{ user.username }}</a></li>
                </ul>
            </nav>
        {% else %}
        {% block navbar %}
            <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
                <a class="navbar-brand" href="{% url 'nutrition:food-list' date %}">Nutrition Tracker</a>
                {% block middle2 %}
                {% endblock %}
                <ul class="navbar-nav mr-only">
                    <li class="nav-item"><a class="nav-link" href="{% url 'register:login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'register:signup' %}">Sign Up</a></li>
                </ul>
            </nav>
        {% endblock %}
        {% endif %}
    </header>

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <div class="alert alert-success" roles="alert">{{ message }}</div>
            {% endif %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" roles="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% block date %}{% endblock %}
    {% block content %} {% endblock %}
        <div class="sidenav">
          <a href="#">Statistics</a>
          <a href="#">Detail Summary</a>
          <a href="#">How to Use</a>
        </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

mysite/nutrition/templates/nutrition/nutrition_data.html
{% block data %}
    <table align=right class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">First</th>
          <th scope="col">Last</th>
          <th scope="col">Handle</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">1</th>
          <td>Mark</td>
          <td>Otto</td>
          <td>@mdo</td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td>Jacob</td>
          <td>Thornton</td>
          <td>@fat</td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td>Larry</td>
          <td>the Bird</td>
          <td>@twitter</td>
        </tr>
      </tbody>
    </table>
{% endblock %}